# Generated by Django 3.2.8 on 2021-11-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goggles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('img', models.CharField(max_length=200)),
                ('p_url', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'goggles',
            },
        ),
        migrations.CreateModel(
            name='Snowboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('img', models.CharField(max_length=200)),
                ('p_url', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'snowboard',
            },
        ),
    ]
