# Generated by Django 3.2.8 on 2021-11-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_goggles_snowboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snowboard',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
